## Gradle Properties for Recon Silk Spawners
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Parchment Mappings and Versions
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.13
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
neo_version=21.1.234
neo_version_range=[21.1.0,)
loader_version_range=[4,)

## Mod Properties
mod_id=bigshopguys
mod_name=Big Shop Guys
mod_license=All Rights Reserved
mod_version=0.0.1
mod_group_id=com.bigchadguys
mod_authors=Recon Halcyon
mod_description=Custom Shop Framework